### PR TITLE
fixed author

### PR DESCRIPTION
**Pull request by machisuji**

### CODE REVIEW

**Comment by tessi** [comment]
:trollface:

**Comment by cratz** [comment]
Merged !!!

**Comment by myabc** [comment]
:+1:

**Comment by tessi** [comment]
Seriously, though. Does anyone care to have a contributors.md or something? Does any maintainer want to be mentioned somehere? It's not like I'm the only person doing things here :)

**Comment by machisuji** [comment]
Oh well, it was worth a try. Always on the lookout for ways to widen my open source portfolio. ;)

If someone wants such a contributors.md they can open a PR for it. :dancer: 

Closing this one.

**Comment by cratz** [comment]
I don't care.
Git will tell the truth... ;) except some crazy guys like @machisuji will do ähhh Things ...

**Comment by machisuji** [comment]
Good idea!

**Comment by tessi** [comment]
xD

**Comment by cratz** [comment]
Force push forever

**Pull request closed without merging**
